### ISSUE TITLE
can't read 3.14 ggpk

### ISSUE THREAD

**Issue by Gyeongb1n** [aianlinb/LibGGPK2#10]
Could you please update?

**Comment by Gyeongb1n** [comment]
can't read 'BaseItemTypes.dat' , 'MonsterVarieties.dat'

**Comment by aianlinb** [comment]
Every new league starts, you have to wait for DatDefinitions.json to be updated for reading dat files

**Comment by Gyeongb1n** [comment]
Can I know when it will be updated?

**Comment by aianlinb** [comment]
@Gyeongb1n Updated
