### ISSUE TITLE
大大安安，又來麻煩你了， v0.12.6在Save Chests.dat64后只能進入城鎮，進入有有箱子的地圖游戲會直接關閉消失掉。

### ISSUE THREAD

**Issue by Acer-bdog** [aianlinb/LibGGPK2#19]
大大安安， 又來打擾你了，v0.12.6在Save Chests.dat64后只能進入城鎮和藏匿處，進入有箱子的地圖游戲會沒有任何提示直接關閉消失掉。
只是用v0.12.6 打開Chests.dat64檔，沒有對Chests.dat64檔做任何修改，按下Save保存，也會是這樣進入有箱子的地圖就會沒有任何提示游戲直接關閉消失，但是游戲任何地圖都會有chests箱子，不管是十個章節地圖還是異界地圖。

**Comment by Acer-bdog** [comment]
在v0.12.4 Save Chests.dat64后能正常進行游戲。

**Comment by aianlinb** [comment]
Fixed in v0.12.7

**Comment by aianlinb** [comment]
感謝你一直幫我找出Bug，dat的編輯功能剛實作出來，問題有點多請見諒
