### ISSUE TITLE
大大安安，又又來麻煩你了，v0.12.17在Save Mods.dat64進入游戲后過一會兒游戲會無響應然後關閉消失掉。

### ISSUE THREAD

**Issue by Acer-bdog** [aianlinb/LibGGPK2#27]
大大安安，又來麻煩你了，v0.12.17在Save Mods.dat64進入游戲后過一會兒游戲會無響應然後關閉消失掉。
直接打開Mods.dat64點Save保存，不修改任何文字，也是一樣會過一會兒游戲無響應后關閉消失，用Recovery從游戲服務器更新文檔后就能夠正常進行游戲，不會過一會兒關閉消失。
而且不能點倉庫，不能打開角色背包，只要進行開倉庫和角色背包的操作，大概率游戲會關閉。

**Comment by aianlinb** [comment]
Fixed in v0.13.0
