### ISSUE TITLE
export doesn't contain full path structure of directory

### ISSUE THREAD

**Issue by nopcall** [aianlinb/LibGGPK2#3]
when export a selected directory, 
just got a single direcotry exported without full path , 
that's inconvenience to import.

**Comment by aianlinb** [comment]
You can use cmd.exe to create the folder first.
For example:
`mkdir ROOT\Bundles2\Metadata\Effects`

**Comment by aianlinb** [comment]
By the way, you can right click a directory on TreeView and click Replace, then you can just select the directory without full path to import.
