### ISSUE TITLE
delete files and folder inside contentpkk?

### ISSUE THREAD

**Issue by zerger3** [aianlinb/LibGGPK2#31]
hi i want to remove some spells from the content ggpk but i did not see an option to delete files?

if i try to import an empty folder it doesnt work nor can i delete files directly. any ideas?

**Comment by aianlinb** [comment]
Changing the directory structure (like add/remove/rename a file or folder) is currently not supported.
Maybe you can try to leave it empty or something else . . .

**Comment by aianlinb** [comment]
This feature will be implemented in [LibGGPK3](https://github.com/aianlinb/LibGGPK3) in the future

**Comment by zerger3** [comment]
:(
