### ISSUE TITLE
Quotes inside CSV fields are not properly escaped

### ISSUE THREAD

**Issue by d07RiV** [aianlinb/LibGGPK2#32]
When exporting MonsterVarieties, the resulting file has the following line

    ... ,Musky "Two-Eyes" Grenn, ...

This is not valid CSV according to specification, and needs to be escaped.

**Comment by aianlinb** [comment]
Fixed in v0.13.6 https://github.com/aianlinb/LibGGPK2/commit/bfd78dde305b569204436bf8aa3b1fd510fc6205
