### ISSUE TITLE
Game client overwrites ggpk every time it starts!

### ISSUE THREAD

**Issue by Hexxxadecimal** [aianlinb/LibGGPK2#37]
I replaced a couple of npc dialog files with similar filenames, but at startup the client somehow realized that the files were not original and downloaded them. Is there any way to bypass the startup check? or by what criteria does the client, in addition to the file name, understand that it is not original?

**Comment by aianlinb** [comment]
This shouldn't happen with LibGGPK2, because it won't change the hash of directories which the game used to detect file changes
Can you provide more information?

**Comment by Hexxxadecimal** [comment]
I thought that maybe it was because of the different file sizes and made a check: I took one phrase of any NPC, for example Eramir and his phrase "Eramir_01.ogg" which has a path(Bundles2\Audio\Dialogue\NPC\Eramir)
I made the export, launched the client (the download did not happen) 
Then replaced the original file with the previously exported one and launched the client
The client started pumping files(((
so how did I understand: any replacement changes the hash?

**Comment by Hexxxadecimal** [comment]
Thanks, after reinstalling everything worked!
