### ISSUE TITLE
Error report for VisualGGPK2 v0.15.2

### ISSUE THREAD

**Issue by Jock-SSH** [aianlinb/LibGGPK2#39]
Game version: 3.1901.2.1 Tencent version
(The preliminary judgment version does not affect the test results)
Software version: VisualGGPK 0.15.2

Specific problems:
1)ROOT\Bundles2\Data\Simplified Chinese\ArchnemesisMods.dat64
2)ROOT\Bundles2\Data\Simplified Chinese\Chests.dat64
3)ROOT\Bundles2\Data\Simplified Chinese\MonsterVarieties.dat64
(Only these files have been briefly tested, not all of them.)

Try Questions:
After importing the.csv file, the game will be unable to start.
A direct replacement using an existing patch (Data.9.bundle) (using VisualGGPK) does not cause this problem.

Test process:
During the test, it was found that after repeated "export-to-re-import" operation on the.csv file, the number of Spaces in the file would be increased (one space would be increased each time "export-to-re-import"), usually in a structure similar to ", x "(Comma + space + character). Since the "export.csv" file was also carried out through this software, Therefore, we are not sure whether it is the bug in the export process or the import process. For details, please refer to the following figure and description.

After comparing and testing files such as ActiveSkills.dat64, the "add whitespace" problem seems to occur:
A paragraph is located at "[.....]", Because other split test files also have text structures like ", x ", but the absence of "[.....]" does not cause the above problem.

![Snipaste_2022-12-11_15-29-37](https://user-images.githubusercontent.com/57992931/206891551-68bfa096-9d14-472f-ae25-2d31762d4d7c.png)

(The test file has been imported and re-exported twice)

Tip: Translator is used for translation ^_^.

**Comment by aianlinb** [comment]
Fixed in v0.15.3
