### ISSUE TITLE
Questions about unpacking the LakeRooms.dat64 file

### ISSUE THREAD

**Issue by Jock-SSH** [aianlinb/LibGGPK2#40]
In the test study of LibGGPK2, it is found that v0.15.3 cannot unpack the description file. The error of VisualGGPK2 is shown as the following figure.
![1](https://user-images.githubusercontent.com/57992931/208012698-a7eef389-a9ad-400b-9411-141fcfca4606.jpg)

Test process:
1. Edit the paragraph corresponding to LakeRooms in the latest version of github.com/poe-tool-dev/dat-schema (because there is no basis of C# language, the main method is to refer to the format of existing files, cry). The corresponding content was added to "datdefint. json" of "LibGGPK2" (see figure below), but it still cannot be resolved.
![2](https://user-images.githubusercontent.com/57992931/208012767-b8fcefb4-c347-40c5-8154-8c50e1c528f3.png)
2. Use the built-in "Use schema.min.json" function in VisualGGPK2 to retrieve the json file of the online version, but it still cannot be parsed.
3. After testing, the above files can be parsed by using "snosme.github.io/poe-dat-viewer/".

To sum up, we do not know whether the following guesses are correct:
The existing "schema.min.json" does not fully parse the "LakeRooms.dat64", so the result is that the" datdefint. json" modified with the contents of the "schema.min.json" does not fully parse. So VisualGGPK2 reported an error.

Tip: Because I do not have C# language foundation, also is not related practitioners, at present have tried to find a variety of ways to solve the problem, but still can not find a solution will come to ask you, I am very sorry to disturb you, and thank you for the answer.
Because of my love for games and my interest in the processing of Chinese-language files and other related files, I spend time on learning and testing. With a better understanding of the difficulty of parsing POE files, I am deeply impressed by the "LibGGPK" series of software you developed and the problems raised by the software soon received feedback. I would appreciate it very much if I could get your advice. I also hope that one day I can make a contribution to the game community.
Thank you

**Comment by aianlinb** [comment]
> To sum up, we do not know whether the following guesses are correct:
  The existing "schema.min.json" does not fully parse the "LakeRooms.dat64", so the result is that the" datdefint. json" modified with the contents of the "schema.min.json" does not fully parse. So VisualGGPK2 reported an error.

Yes, that's right.

The fact is that the `poe-dat-viewer` also doesn't fully parse.
![image](https://user-images.githubusercontent.com/29705994/208013889-dddbf608-9a28-408d-85dd-878a7157a027.png)
It's still missing a foreignrow and a bool at the end of the file.
