### ISSUE TITLE
Error reading HeistChestRewardsTypes

### ISSUE THREAD

**Issue by Violet-Vibes** [aianlinb/LibGGPK2#48]
![image](https://user-images.githubusercontent.com/19490536/233938931-8f79d7ef-be91-42b5-bfa7-e484acb4ab77.png)

This also happens when using the schema.min.json, 

![image](https://user-images.githubusercontent.com/19490536/233939056-9aacdee8-aaf3-47f3-862a-83b638b331f0.png)

**Comment by aianlinb** [comment]
@Violet-Vibes
Open DatDefinition.json
Find `HeistChestRewardTypes`
Replace it with
```json
	"HeistChestRewardTypes": {
		"Id": "string",
		"Art": "string",
		"RewardTypeName": "string",
		"Unknown0": "row",
		"RewardRoomName": "string",
		"MinLevel": "i32",
		"MaxLevel": "i32",
		"Weight": "i32",
		"RewardRoomName2": "string",
		"HeistJobsKey": "array|foreignrow",
		"Unknown1": "i32",
		"Unknown2": "i32"
	}
```
