### ISSUE TITLE
Error after the latest patch

### ISSUE THREAD

**Issue by ParanoiaIsGreat** [aianlinb/LibGGPK2#49]
GGG seems changed something after the latest patch 3.21.2.
Can you do something about this? An update?
Thx!

![image](https://github.com/aianlinb/LibGGPK2/assets/10475153/829f20cb-cdfb-45ad-b2b8-646d1e5cd1d0)

**Comment by Banaghran** [comment]
[IndexContainer.txt](https://github.com/aianlinb/LibGGPK2/files/12165586/IndexContainer.txt)

quick n dirty, shameless copy paste from https://github.com/SlideWave/Mumurhash264A with fixing the remainder part to be in the right direction

murmur info https://github.com/rarten/ooz/commit/339228c57341d6c359dd93172a55dd32e2f26254

**Comment by ParanoiaIsGreat** [comment]
Thx for the update. But no more update for Visualbundle?

**Comment by aianlinb** [comment]
@ParanoiaIsGreat That project has been archived and will never be updated
Please use SteamMode.bat of VisualGGPK2 instead.
