### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by andregaeta** [aianlinb/LibGGPK2#5]
![image](https://user-images.githubusercontent.com/58143276/104811139-465d3c80-57d8-11eb-8d7e-0cd254ad2b30.png)

This had never happened to me before, started happening out of nowhere. My Content.ggpk seems to be fine, the game is running well. 

It might be a problem on my end, so please don't worry about it, but if it's something you're familiar with, please let me know. Thanks!

**Comment by andregaeta** [comment]
My bad, didn't realize this was already posted, haha. I'll try the fix, thanks!

**Comment by andregaeta** [comment]
FixFreeRecords worked like a charm! Thanks.

**Comment by aianlinb** [comment]
#2
