### ISSUE TITLE
Replace to original files

### ISSUE THREAD

**Issue by Onurtest** [aianlinb/LibGGPK2#6]
I am trying to remove kinetic blast skill effect on Steam. Can you help me please? still I didnt understand this program. When i remove the lines and click save button, bundle location is changing. https://imgur.com/kHF49Ig  i want to remove kinetic blast skill effect but i can't put my changes to original files. How can i do this? Is there any tutorial?

**Comment by aianlinb** [comment]
Bundle will be changed, it's normal.

I do not provide the format of modifying files.

**Comment by aianlinb** [comment]
Fixed https://github.com/aianlinb/LibGGPK2/issues/7
