### ISSUE TITLE
Steam mode not working?

### ISSUE THREAD

**Issue by Onurtest** [aianlinb/LibGGPK2#7]
I am saving the files and open the game nothing changes sir. Can you please try this? Save it and close and then open the program again nothing is change

**Comment by Onurtest** [comment]
I am removing 1 function and write 8 from 9 but when i open the program again it is showing 9 again :/

**Comment by aianlinb** [comment]
Fixed https://github.com/aianlinb/LibGGPK2/releases/tag/v0.8.1
