### ISSUE TITLE
How to use VisualGGPK2?

### ISSUE THREAD

**Issue by Joostarr** [aianlinb/LibGGPK2#8]
Hi, I'd like to use the VisualGGPK2 but I have no idea how to even open it or download it for that matter. I also have no idea how to send you a message or comment so this is the only way I found.

Regards.

**Comment by aianlinb** [comment]
Download here https://github.com/aianlinb/LibGGPK2/releases
Then launch VisualGGPK2.exe and select your ggpk

**Comment by Joostarr** [comment]
Thanks a ton for taking the time to reply! Sorry for using the issues section for this.
