### ISSUE TITLE
How to clear a filter?

### ISSUE THREAD

**Issue by zaafar** [aianlinb/LibGGPK2#9]
Sorry for the noob question, let's say I put the filter ".dat" and press the filter button.
After doing my research, I want to clear the ".dat" filter & show all the files again.
How do I clear it? If I clear the filter field and press "Filter" button again, it makes the application hang.

**Comment by aianlinb** [comment]
Just clear the TextBox and press "Filter"
It will hang for seconds, because of the tree rebuilding

**Comment by zaafar** [comment]
Ah okay. I though it hanged due to some issue. Thanks for the reply!
